name = "omnibackend2"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
usage_model = "unbound"
workers_dev = true

[vars]
FRONTEND_URL = "https://fwea-i.com"
WORKER_BASE_URL = "https://omnibackend2.fweago-flavaz.workers.dev"

RUNPOD_API_URL = "https://rvxah7xwk0ql9p-8000.proxy.runpod.net/"
RUNPOD_API_KEY = "$RUNPOD_API_KEY"

[assets]
directory = "./public"

# --- Cloudflare AI binding
[ai]
binding = "AI"

# --- R2 storage
[[r2_buckets]]
binding = "AUDIO_STORAGE"
bucket_name = "fwea-audio-storage"

# --- KV namespace
[[kv_namespaces]]
binding = "PROFANITY_LISTS"
id = "6a64a5d1cb7b4ac5bcaefaec65129a66"

# --- D1 database
[[d1_databases]]
binding = "DB"
database_name = "fwea-database"
database_id = "e86cdc5e-9076-4076-a4e9-9f05591c3119"

# --- Durable Object
[durable_objects]
bindings = [
  { name = "PROCESSING_STATE", class_name = "ProcessingStateV2" }
]

# --- Queues
[[queues.producers]]
binding = "TRANSCODE_QUEUE"
queue = "audio-transcoding-queue"

[[queues.consumers]]
queue = "audio-transcoding-queue"
worker = "omnibackend2"
max_batch_size = 10
max_batch_timeout = 30

[observability]
enabled = true
head_sampling_rate = 1.0

[build]
command = "echo 'No build step required'"

[env.production]
name = "omnibackend2"
vars = { FRONTEND_URL = "https://fwea-i.com", WORKER_BASE_URL = "https://omnibackend2.fweago-flavaz.workers.dev" }

[env.staging]
name = "omnibackend2-staging"
vars = { FRONTEND_URL = "https://staging.fwea-i.com", WORKER_BASE_URL = "https://omnibackend2-staging.fweago-flavaz.workers.dev" }

[env.development]
name = "omnibackend2-dev"
vars = { FRONTEND_URL = "http://localhost:3000", WORKER_BASE_URL = "http://localhost:8787" }

[[migrations]]
tag = "v1"
new_classes = ["ProcessingStateV2"]

keep_vars = true

[placement]
mode = "smart"

[limits]
cpu_ms = 30000

send_metrics = true

[triggers]
crons = ["0 0 * * *"]

# NOTE: TRANSCODER service binding removed to avoid deploy failure
# (code 10141: target script/environment not found). If/when you deploy a
# separate Worker for transcoding, re-add:
# [[services]]
# binding = "TRANSCODER"
# service = "audio-transcoder-service"   # <-- exact Worker name
# environment = "production"              # <-- environment that actually exists
